name: Arduino Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ArduinoBuild:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Arduino CLI
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "/home/runner/work/basic_git_test/basic_git_test/bin" >> $GITHUB_PATH

      # Configure Arduino CLI
      - name: Configure Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      # Compile your sketch
      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn arduino:avr:uno Blink Blink --output-dir build

      - name: Upload compiled binaries
        uses: actions/upload-artifact@v3
        with:
          name: arduino-binaries
          path: build
   
